using System;

namespace AppBusiness.Data.DTOs
{
    public class ParamRekeningAirDto
    {
        public int? IdPdam { get; set; }
        public int? IdPelangganAir { get; set; }
        public int? IdPeriode { get; set; }
        public int? IdGolongan { get; set; }
        public int? IdDiameter { get; set; }
        public int? IdRayon { get; set; }
        public int? IdKelurahan { get; set; }
        public int? IdKolektif { get; set; }
        public int? IdAdministrasiLain { get; set; }
        public int? IdPemeliharaanLain { get; set; }
        public int? IdRetribusiLain { get; set; }
        public int? IdStatus { get; set; }
        public int? IdFlag { get; set; }
        public decimal? StanLalu { get; set; }
        public decimal? StanSkrg { get; set; }
        public decimal? StanAngkat { get; set; }
        public decimal? Pakai { get; set; }
        public decimal? PakaiKalkulasi { get; set; }
        public decimal? BiayaPemakaian { get; set; }
        public decimal? Administrasi { get; set; }
        public decimal? Pemeliharaan { get; set; }
        public decimal? Retribusi { get; set; }
        public decimal? Pelayanan { get; set; }
        public decimal? AirLimbah { get; set; }
        public decimal? DendaPakai0 { get; set; }
        public decimal? AdministrasiLain { get; set; }
        public decimal? PemeliharaanLain { get; set; }
        public decimal? RetribusiLain { get; set; }
        public decimal? Meterai { get; set; }
        public decimal? Rekair { get; set; }
        public decimal? Denda { get; set; }
        public decimal? Ppn { get; set; }
        public decimal? Total { get; set; }
        public int? HapusSecaraAkuntansi { get; set; }
        public DateTime? WaktuHapusSecaraAkuntansi { get; set; }
        public bool? FlagBaca { get; set; }
        public int? MetodeBaca { get; set; }
        public DateTime? WaktuBaca { get; set; }
        public string PetugasBaca { get; set; }
        public string Kelainan { get; set; }
        public decimal? StanBaca { get; set; }
        public string Memo { get; set; }
        public string Lampiran { get; set; }
        public bool? Taksasi { get; set; }
        public bool? Taksir { get; set; }
        public int? FlagRequestBacaUlang { get; set; }
        public string RequestBacaUlang { get; set; }
        public DateTime? WaktuUpdateRequestBacaUlang { get; set; }
        public bool? FlagKoreksi { get; set; }
        public DateTime? WaktuKoreksi { get; set; }
        public bool? FlagVerifikasi { get; set; }
        public DateTime? WaktuVerifikasi { get; set; }
        public bool? FlagPublish { get; set; }
        public DateTime? WaktuPublish { get; set; }
        public bool? FlagUpload { get; set; }
        public DateTime? WaktuUpload { get; set; }
        public string NomorTransaksi { get; set; }
        public bool? StatusTransaksi { get; set; }
        public int? TahunTransaksi { get; set; }
        public DateTime? WaktuTransaksi { get; set; }
        public int? IdUserTransaksi { get; set; } // kasir
        public int? IdLoket { get; set; }
        public int? IdUserRequest { get; set; }
        public int? IdMerekMeter { get; set; }
        public int? IdKondisiMeter { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool? AdaFotoMeter { get; set; }
        public bool? AdaFotoRumah { get; set; }
        public bool? AdaVideo { get; set; }
        public bool? FlagMinimumPakai { get; set; }
        public decimal? PakaiBulanLalu { get; set; }
        public decimal? Pakai2BulanLalu { get; set; }
        public string KelainanBulanLalu { get; set; }
        public string Kelainan2BulanLalu { get; set; }
        public bool IsSelected { get; set; }
        public int? IdUserKasir { get; set; }
    }

    public class ParamRekeningAirFilterDto : ParamRekeningAirDto
    {
        public string NoSamb { get; set; }
        public string NoSeriMeter { get; set; }
        public string NoRekening { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public int? KodePeriode { get; set; }
        public string NamaPeriode { get; set; }
        public string KodeGolongan { get; set; }
        public string NamaGolongan { get; set; }
        public string Kategori { get; set; }
        public string KodeDiameter { get; set; }
        public string NamaDiameter { get; set; }
        public string KodeRayon { get; set; }
        public string NamaRayon { get; set; }
        public int? IdArea { get; set; }
        public string KodeArea { get; set; }
        public string NamaArea { get; set; }
        public int? IdWilayah { get; set; }
        public string KodeWilayah { get; set; }
        public string NamaWilayah { get; set; }
        public string KodeKelurahan { get; set; }
        public string NamaKelurahan { get; set; }
        public int? IdKecamatan { get; set; }
        public string KodeKecamatan { get; set; }
        public string NamaKecamatan { get; set; }
        public string KodeCabang { get; set; }
        public string NamaCabang { get; set; }
        public int? IdBlok { get; set; }
        public int? IdCabang { get; set; }
        public string KodeKolektif { get; set; }
        public string NamaKolektif { get; set; }
        public string NamaStatus { get; set; }
        public string NamaFlag { get; set; }
        public decimal? PakaiAwal { get; set; }
        public decimal? PakaiAkhir { get; set; }
        public decimal? RekairAwal { get; set; }
        public decimal? RekairAkhir { get; set; }
        public string NamaMetodeBaca { get; set; }
        public DateTime? TglBayarAwal { get; set; }
        public DateTime? TglBayarAkhir { get; set; }
        public string NamaUser { get; set; }
        public string KodeLoket { get; set; }
        public string NamaLoket { get; set; }
        public string AlasanBatal { get; set; }
        public string NamaMerekMeter { get; set; }
        public string Lainnya { get; set; }
        public decimal? LuasRumahAwal { get; set; }
        public decimal? LuasRumahAkhir { get; set; }
        public decimal? RekAirAwal { get; set; }
        public decimal? RekAirAkhir { get; set; }
        public DateTime? WaktuKoreksiAwal { get; set; }
        public DateTime? WaktuKoreksiAkhir { get; set; }
        public DateTime? WaktuPublishAwal { get; set; }
        public DateTime? WaktuPublishAkhir { get; set; }
        public DateTime? WaktuUploadAwal { get; set; }
        public DateTime? WaktuUploadAkhir { get; set; }
        public DateTime? WaktuTransaksiAwal { get; set; }
        public DateTime? WaktuTransaksiAkhir { get; set; }
        public DateTime? WaktuBacaAwal { get; set; }
        public DateTime? WaktuBacaAkhir { get; set; }
        public DateTime? WaktuUpdateRequestBacaUlangAwal { get; set; }
        public DateTime? WaktuUpdateRequestBacaUlangAkhir { get; set; }
        public DateTime? WaktuVerifikasiAwal { get; set; }
        public DateTime? WaktuVerifikasiAkhir { get; set; }
        public decimal? StanAngkatAwal { get; set; }
        public decimal? StanAngkatAkhir { get; set; }
        public decimal? StanLaluAwal { get; set; }
        public decimal? StanLaluAkhir { get; set; }
        public decimal? StanSkrgAwal { get; set; }
        public decimal? StanSkrgAkhir { get; set; }
        public int? IdKolektifTransaksi { get; set; }

    }
}
